---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


## NOTICE on items in this file:
##   * If you use anything in the *._git_install_branch field that is not a TAG
##     make sure to leave an in-line comment as to "why".

## For the sake of anyone else editing this file:
##   * If you add services to this file please do so in alphabetical order.
##   * Every entry should be name spaced with the name of the client followed by an "_"
##   * All items with this file should be separated by `name_` note that the name of the
##     package should be one long name with no additional `_` separating it.


### Before this is shipped all of these services should have a tag set as the branch,
### or have a comment / reason attached to them as to why a tag can not work.

### HEAD as of 20.04.2022 ###

## Global Requirements
requirements_git_repo: https://opendev.org/openstack/requirements
requirements_git_install_branch: 31511864b6461ed30b262e584410795bf0d7e24c
requirements_git_track_branch: stable/victoria

## Adjutant service
adjutant_git_repo: https://opendev.org/openstack/adjutant
adjutant_git_install_branch: victoria-eom
adjutant_git_track_branch: stable/victoria

## Adjutant dashboard plugin
adjutant_dashboard_git_repo: https://opendev.org/openstack/adjutant-ui
adjutant_dashboard_git_install_branch: 104c474479e9a89d22b96777378ff59983c03393
adjutant_dashboard_git_track_branch: master

## Aodh service
aodh_git_repo: https://opendev.org/openstack/aodh
aodh_git_install_branch: victoria-eom
aodh_git_track_branch: stable/victoria


## Barbican service
barbican_git_repo: https://opendev.org/openstack/barbican
barbican_git_install_branch: victoria-eom
barbican_git_track_branch: stable/victoria


## Barbican dashboard plugin
barbican_dashboard_git_repo: https://opendev.org/openstack/barbican-ui
barbican_dashboard_git_install_branch: 3a78a743426376250f43508d4281e86c75067271
barbican_dashboard_git_track_branch: master


## Ceilometer service
ceilometer_git_repo: https://opendev.org/openstack/ceilometer
ceilometer_git_install_branch: victoria-eom
ceilometer_git_track_branch: stable/victoria


## Cinder service
cinder_git_repo: https://opendev.org/openstack/cinder
cinder_git_install_branch: victoria-eom
cinder_git_track_branch: stable/victoria


## Cloudkitty service
cloudkitty_git_repo: https://opendev.org/openstack/cloudkitty
cloudkitty_git_install_branch: victoria-eom
cloudkitty_git_track_branch: stable/victoria


## Cloudkitty dashboard plugin
cloudkitty_dashboard_git_repo: https://opendev.org/openstack/cloudkitty-dashboard
cloudkitty_dashboard_git_install_branch: victoria-eom
cloudkitty_dashboard_git_track_branch: stable/victoria


## Designate service
designate_git_repo: https://opendev.org/openstack/designate
designate_git_install_branch: victoria-eom
designate_git_track_branch: stable/victoria


## Horizon Designate dashboard plugin
designate_dashboard_git_repo: https://opendev.org/openstack/designate-dashboard
designate_dashboard_git_install_branch: victoria-eom
designate_dashboard_git_track_branch: stable/victoria


## Glance service
glance_git_repo: https://opendev.org/openstack/glance
glance_git_install_branch: victoria-eom
glance_git_track_branch: stable/victoria


## Heat service
heat_git_repo: https://opendev.org/openstack/heat
heat_git_install_branch: victoria-eom
heat_git_track_branch: stable/victoria

## Horizon Heat dashboard plugin
heat_dashboard_git_repo: https://opendev.org/openstack/heat-dashboard
heat_dashboard_git_install_branch: victoria-eom
heat_dashboard_git_track_branch: stable/victoria

## Horizon service
horizon_git_repo: https://opendev.org/openstack/horizon
horizon_git_install_branch: victoria-eom
horizon_git_track_branch: stable/victoria

## Horizon Ironic dashboard plugin
ironic_dashboard_git_repo: https://opendev.org/openstack/ironic-ui
ironic_dashboard_git_install_branch: victoria-eom
ironic_dashboard_git_track_branch: stable/victoria

## Horizon Magnum dashboard plugin
magnum_dashboard_git_repo: https://opendev.org/openstack/magnum-ui
magnum_dashboard_git_install_branch: victoria-eom
magnum_dashboard_git_track_branch: stable/victoria

## Horizon Masakari dashboard plugin
masakari_dashboard_git_repo: https://opendev.org/openstack/masakari-dashboard
masakari_dashboard_git_install_branch: victoria-eom
masakari_dashboard_git_track_branch: stable/victoria


## Horizon Sahara dashboard plugin
sahara_dashboard_git_repo: https://opendev.org/openstack/sahara-dashboard
sahara_dashboard_git_install_branch: victoria-eom
sahara_dashboard_git_track_branch: stable/victoria


## Keystone service
keystone_git_repo: https://opendev.org/openstack/keystone
keystone_git_install_branch: victoria-eom
keystone_git_track_branch: stable/victoria


## Manila service
manila_git_repo: https://opendev.org/openstack/manila
manila_git_install_branch: victoria-eom
manila_git_track_branch: stable/victoria


## Neutron service
neutron_git_repo: https://opendev.org/openstack/neutron
neutron_git_install_branch: victoria-eom
neutron_git_track_branch: stable/victoria

neutron_vpnaas_git_repo: https://opendev.org/openstack/neutron-vpnaas
neutron_vpnaas_git_install_branch: victoria-eom
neutron_vpnaas_git_track_branch: stable/victoria


neutron_dynamic_routing_git_repo: https://opendev.org/openstack/neutron-dynamic-routing
neutron_dynamic_routing_git_install_branch: victoria-eom
neutron_dynamic_routing_git_track_branch: stable/victoria

# Networking calico follows master
networking_calico_git_repo: https://github.com/projectcalico/networking-calico
networking_calico_git_install_branch: 1a588c56645333ab044cf98661498d4e601d1590
networking_calico_git_track_branch: release-v3.16

networking_odl_git_repo: https://opendev.org/openstack/networking-odl
networking_odl_git_install_branch: victoria-eom
networking_odl_git_track_branch: stable/victoria

networking_bgpvpn_git_repo: https://opendev.org/openstack/networking-bgpvpn
networking_bgpvpn_git_install_branch: victoria-eom
networking_bgpvpn_git_track_branch: stable/victoria

networking_sfc_git_repo: https://opendev.org/openstack/networking-sfc
networking_sfc_git_install_branch: victoria-eom
networking_sfc_git_track_branch: stable/victoria

networking_generic_switch_git_repo: https://opendev.org/openstack/networking-generic-switch
networking_generic_switch_git_install_branch: victoria-eom
networking_generic_switch_git_track_branch: stable/victoria

networking_nsx_git_repo: https://opendev.org/x/vmware-nsx
networking_nsx_git_install_branch: victoria-eom
networking_nsx_git_track_branch: stable/victoria

networking_nsxlib_git_repo: https://opendev.org/x/vmware-nsxlib
networking_nsxlib_git_install_branch: victoria-eom
networking_nsxlib_git_track_branch: stable/victoria

## Nova service
nova_git_repo: https://opendev.org/openstack/nova
nova_git_install_branch: victoria-eom
nova_git_track_branch: stable/victoria


## Sahara service
sahara_git_repo: https://opendev.org/openstack/sahara
sahara_git_install_branch: victoria-eom
sahara_git_track_branch: stable/victoria


## Senlin service
senlin_git_repo: https://opendev.org/openstack/senlin
senlin_git_install_branch: victoria-eom
senlin_git_track_branch: stable/victoria


## Swift service
swift_git_repo: https://opendev.org/openstack/swift
swift_git_install_branch: victoria-eom
swift_git_track_branch: stable/victoria


## Ironic service
ironic_git_repo: https://opendev.org/openstack/ironic
ironic_git_install_branch: victoria-eom
ironic_git_track_branch: stable/victoria


## Ironic inspector service
ironic_inspector_git_repo: https://opendev.org/openstack/ironic-inspector
ironic_inspector_git_install_branch: victoria-eom
ironic_inspector_git_track_branch: stable/victoria


## Magnum service
magnum_git_repo: https://opendev.org/openstack/magnum
magnum_git_install_branch: victoria-eom
magnum_git_track_branch: stable/victoria

## Masakari service
masakari_git_repo: https://opendev.org/openstack/masakari
masakari_git_install_branch: victoria-eom
masakari_git_track_branch: stable/victoria

## Masakari monitors services
masakari_monitors_git_repo: https://opendev.org/openstack/masakari-monitors
masakari_monitors_git_install_branch: victoria-eom
masakari_monitors_git_track_branch: stable/victoria

## Mistral service
mistral_git_repo: https://opendev.org/openstack/mistral
mistral_git_install_branch: victoria-eom
mistral_git_track_branch: stable/victoria

mistral_extra_git_repo: https://opendev.org/openstack/mistral-extra
mistral_extra_git_install_branch: victoria-eom
mistral_extra_git_track_branch: stable/victoria

## Murano service
murano_git_repo: https://opendev.org/openstack/murano
murano_git_install_branch: victoria-eom
murano_git_track_branch: stable/victoria

murano_dashboard_git_repo: https://opendev.org/openstack/murano-dashboard
murano_dashboard_git_install_branch: victoria-eom
murano_dashboard_git_track_branch: stable/victoria

## Trove service
trove_git_repo: https://opendev.org/openstack/trove
trove_git_install_branch: victoria-eom
trove_git_track_branch: stable/victoria

## Horizon Trove dashboard plugin
trove_dashboard_git_repo: https://opendev.org/openstack/trove-dashboard
trove_dashboard_git_install_branch: victoria-eom
trove_dashboard_git_track_branch: stable/victoria


## Octavia service
octavia_git_repo: https://opendev.org/openstack/octavia
octavia_git_install_branch: victoria-eom
octavia_git_track_branch: stable/victoria


## Panko service
panko_git_repo: https://opendev.org/openstack/panko
panko_git_install_branch: victoria-eom
panko_git_track_branch: stable/victoria


## Placement service
placement_git_repo: https://opendev.org/openstack/placement
placement_git_install_branch: victoria-eom
placement_git_track_branch: stable/victoria


## Tacker service
tacker_git_repo: https://opendev.org/openstack/tacker
tacker_git_install_branch: victoria-eom
tacker_git_track_branch: stable/victoria


## Horizon Octavia dashboard plugin
octavia_dashboard_git_repo: https://opendev.org/openstack/octavia-dashboard
octavia_dashboard_git_install_branch: victoria-eom
octavia_dashboard_git_track_branch: stable/victoria


## Blazar service
blazar_git_repo: https://opendev.org/openstack/blazar
blazar_git_install_branch: victoria-eom
blazar_git_track_branch: stable/victoria

## Blazar Nova Service
blazar_nova_git_repo: https://opendev.org/openstack/blazar-nova
blazar_nova_git_install_branch: victoria-eom
blazar_nova_git_track_branch: stable/victoria

## Zun service
zun_git_repo: https://opendev.org/openstack/zun
zun_git_install_branch: victoria-eom
zun_git_track_branch: stable/victoria

## Zun kuryr service
zun_kuryr_git_repo: https://opendev.org/openstack/kuryr-libnetwork
zun_kuryr_git_install_branch: victoria-eom
zun_kuryr_git_track_branch: stable/victoria

## Zun kuryr library
zun_kuryr_lib_git_repo: https://opendev.org/openstack/kuryr
zun_kuryr_lib_git_install_branch: victoria-eom
zun_kuryr_lib_git_track_branch: stable/victoria
