---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


## NOTICE on items in this file:
##   * If you use anything in the *._git_install_branch field that is not a TAG
##     make sure to leave an in-line comment as to "why".

## For the sake of anyone else editing this file:
##   * If you add services to this file please do so in alphabetical order.
##   * Every entry should be name spaced with the name of the client followed by an "_"
##   * All items with this file should be separated by `name_` note that the name of the
##     package should be one long name with no additional `_` separating it.


### Before this is shipped all of these services should have a tag set as the branch,
### or have a comment / reason attached to them as to why a tag can not work.

### HEAD as of 17.01.2023 ###

## Global Requirements
requirements_git_repo: https://opendev.org/openstack/requirements
requirements_git_install_branch: 707da594d13b7f1ed47800660aaa2a8a804689df
requirements_git_track_branch: stable/yoga

## Adjutant service
adjutant_git_repo: https://opendev.org/openstack/adjutant
adjutant_git_install_branch: d9ddbd6d3e5aec42a8bc6b2e26c20f16c92b38a4
adjutant_git_track_branch: stable/yoga

## Adjutant dashboard plugin
adjutant_dashboard_git_repo: https://opendev.org/openstack/adjutant-ui
adjutant_dashboard_git_install_branch: 4464d9cb53beb1f5b14a51c49a84fc0efe925aec
adjutant_dashboard_git_track_branch: stable/yoga

## Aodh service
aodh_git_repo: https://opendev.org/openstack/aodh
aodh_git_install_branch: 849a0a0219e6f060efa1d0530afa2d6df2897501
aodh_git_track_branch: None # We do not bump aodh due to https://storyboard.openstack.org/#!/story/2010225


## Barbican service
barbican_git_repo: https://opendev.org/openstack/barbican
barbican_git_install_branch: f5147debb9af3eb9b5a9ce61d8c5177470bdfc9a
barbican_git_track_branch: stable/yoga


## Barbican dashboard plugin
barbican_dashboard_git_repo: https://opendev.org/openstack/barbican-ui
barbican_dashboard_git_install_branch: 3a78a743426376250f43508d4281e86c75067271
barbican_dashboard_git_track_branch: master


## Ceilometer service
ceilometer_git_repo: https://opendev.org/openstack/ceilometer
ceilometer_git_install_branch: 3f775ea4576ab1201dddc781ef906f2e388b7eca
ceilometer_git_track_branch: stable/yoga


## Cinder service
cinder_git_repo: https://opendev.org/openstack/cinder
cinder_git_install_branch: 4cef5c0c4244fff8ec02809cbf295267b3f6bde9
cinder_git_track_branch: stable/yoga


## Cloudkitty service
cloudkitty_git_repo: https://opendev.org/openstack/cloudkitty
cloudkitty_git_install_branch: 221a5caa56e0bfc795278f54a56167d95efd9e62
cloudkitty_git_track_branch: stable/yoga


## Cloudkitty dashboard plugin
cloudkitty_dashboard_git_repo: https://opendev.org/openstack/cloudkitty-dashboard
cloudkitty_dashboard_git_install_branch: f3f3b9f2656c329ddc5d74179b5ceffb4fa8fb50
cloudkitty_dashboard_git_track_branch: stable/yoga


## Designate service
designate_git_repo: https://opendev.org/openstack/designate
designate_git_install_branch: 6664bb441228850c1aa544b24d56986f18124bfb
designate_git_track_branch: stable/yoga


## Horizon Designate dashboard plugin
designate_dashboard_git_repo: https://opendev.org/openstack/designate-dashboard
designate_dashboard_git_install_branch: 2a96e2764cd7d4534adc7084f241db0bcae277c5
designate_dashboard_git_track_branch: stable/yoga


## Glance service
glance_git_repo: https://opendev.org/openstack/glance
glance_git_install_branch: 3f6c689b7241bc20bc9f7ed398058bc312f81df3
glance_git_track_branch: stable/yoga


## Heat service
heat_git_repo: https://opendev.org/openstack/heat
heat_git_install_branch: c3a8e3d64ebb37ab83b3cebb868cd68d4135f59d
heat_git_track_branch: stable/yoga

## Horizon Heat dashboard plugin
heat_dashboard_git_repo: https://opendev.org/openstack/heat-dashboard
heat_dashboard_git_install_branch: 36ae65ee9da09aa486541740b58ffd6aea748513
heat_dashboard_git_track_branch: stable/yoga

## Horizon service
horizon_git_repo: https://opendev.org/openstack/horizon
horizon_git_install_branch: 8911e2b8c10d5ea0efbdd896eb5292fc0c7f276f
horizon_git_track_branch: stable/yoga

## Horizon Ironic dashboard plugin
ironic_dashboard_git_repo: https://opendev.org/openstack/ironic-ui
ironic_dashboard_git_install_branch: 5380524aa8c8b4c189dcef3548ae9c803975b66f
ironic_dashboard_git_track_branch: stable/yoga

## Horizon Magnum dashboard plugin
magnum_dashboard_git_repo: https://opendev.org/openstack/magnum-ui
magnum_dashboard_git_install_branch: ea8a0d3a610b37d9d6bdcb08058d5ceeec722cab
magnum_dashboard_git_track_branch: stable/yoga

## Horizon Masakari dashboard plugin
masakari_dashboard_git_repo: https://opendev.org/openstack/masakari-dashboard
masakari_dashboard_git_install_branch: de7b74d28eea77555df23b364451b847aa966eaf
masakari_dashboard_git_track_branch: stable/yoga


## Horizon Sahara dashboard plugin
sahara_dashboard_git_repo: https://opendev.org/openstack/sahara-dashboard
sahara_dashboard_git_install_branch: e37d8f91c28bc5d88d56013fa3897576c5c27ef4
sahara_dashboard_git_track_branch: stable/yoga


## Keystone service
keystone_git_repo: https://opendev.org/openstack/keystone
keystone_git_install_branch: a26b9c20de7103b1cb6cdd43bd2f2cca9a29fa2f
keystone_git_track_branch: stable/yoga


## Manila service
manila_git_repo: https://opendev.org/openstack/manila
manila_git_install_branch: 725e4cc43dde51c98520cb4b66a1f57aaef4038b
manila_git_track_branch: stable/yoga


## Neutron service
neutron_git_repo: https://opendev.org/openstack/neutron
neutron_git_install_branch: 2a2fda29c9a934174310627f10ade7ffe90879c1
neutron_git_track_branch: stable/yoga

neutron_vpnaas_git_repo: https://opendev.org/openstack/neutron-vpnaas
neutron_vpnaas_git_install_branch: 52cfcb31096bd28adef62a38863cde59c2e5313f
neutron_vpnaas_git_track_branch: stable/yoga


neutron_dynamic_routing_git_repo: https://opendev.org/openstack/neutron-dynamic-routing
neutron_dynamic_routing_git_install_branch: 0fad6a8b9bd8dfcf92c745c3cd5a2d9d9ed293fa
neutron_dynamic_routing_git_track_branch: stable/yoga

# Networking calico follows master
networking_calico_git_repo: https://github.com/projectcalico/networking-calico
networking_calico_git_install_branch: 69ada593823daaecb997114e694522449839f131
networking_calico_git_track_branch: release-v3.21

networking_odl_git_repo: https://opendev.org/openstack/networking-odl
networking_odl_git_install_branch: e885791c559586bac331c7f7ab9d007447cfa58e
networking_odl_git_track_branch: stable/yoga

networking_bgpvpn_git_repo: https://opendev.org/openstack/networking-bgpvpn
networking_bgpvpn_git_install_branch: 370bf1381fae437899c13a3512090dff58661e45
networking_bgpvpn_git_track_branch: stable/yoga

networking_sfc_git_repo: https://opendev.org/openstack/networking-sfc
networking_sfc_git_install_branch: 2d9e61daf20436354e668d76089f5a79baa938bd
networking_sfc_git_track_branch: stable/yoga

networking_generic_switch_git_repo: https://opendev.org/openstack/networking-generic-switch
networking_generic_switch_git_install_branch: a5926116a3fa5fd0cdd74d4f5d97e1e54514f737
networking_generic_switch_git_track_branch: stable/yoga

networking_nsx_git_repo: https://opendev.org/x/vmware-nsx
networking_nsx_git_install_branch: 0253265f75f63d5619b30f16a6b64459dec79d82
networking_nsx_git_track_branch: master

networking_nsxlib_git_repo: https://opendev.org/x/vmware-nsxlib
networking_nsxlib_git_install_branch: 44ac0a020a7db6b1842a61a5f3d4de229d03b37f
networking_nsxlib_git_track_branch: master

## Nova service
nova_git_repo: https://opendev.org/openstack/nova
nova_git_install_branch: a45cf404bf71eac32641d88350a32cf92ae0eb53
nova_git_track_branch: stable/yoga


## Sahara service
sahara_git_repo: https://opendev.org/openstack/sahara
sahara_git_install_branch: 4af54a062c3536ecce37e1386ee549fadbf3392d
sahara_git_track_branch: stable/yoga


## Senlin service
senlin_git_repo: https://opendev.org/openstack/senlin
senlin_git_install_branch: 804056e856fb80bc881f6ef22eb57bc4adf7a287
senlin_git_track_branch: stable/yoga


## Swift service
swift_git_repo: https://opendev.org/openstack/swift
swift_git_install_branch: 4107219442a4ac8d902c0fef5157bd39e808983f
swift_git_track_branch: stable/yoga


## Ironic service
ironic_git_repo: https://opendev.org/openstack/ironic
ironic_git_install_branch: 26573bed3aa64f8fdb81cada528d30373060c766
ironic_git_track_branch: stable/yoga


## Ironic inspector service
ironic_inspector_git_repo: https://opendev.org/openstack/ironic-inspector
ironic_inspector_git_install_branch: 5da8e980d6bc6e501971d7f9c336ea743316b2b9
ironic_inspector_git_track_branch: stable/yoga


## Magnum service
magnum_git_repo: https://opendev.org/openstack/magnum
magnum_git_install_branch: b8e50f26a963375a7707ed42dc5d36c17d1f0b38
magnum_git_track_branch: stable/yoga

## Masakari service
masakari_git_repo: https://opendev.org/openstack/masakari
masakari_git_install_branch: 78008dad073688049f095db59a750c6cf3dcf726
masakari_git_track_branch: stable/yoga

## Masakari monitors services
masakari_monitors_git_repo: https://opendev.org/openstack/masakari-monitors
masakari_monitors_git_install_branch: af3c058f959ed036e01180e922f1e7d32e60cda1
masakari_monitors_git_track_branch: stable/yoga

## Mistral service
mistral_git_repo: https://opendev.org/openstack/mistral
mistral_git_install_branch: 21867b48c7f223c39fb00b244df49898d337dee2
mistral_git_track_branch: stable/yoga

mistral_extra_git_repo: https://opendev.org/openstack/mistral-extra
mistral_extra_git_install_branch: 4beae859c64356a77f64d7135426fcf0c6f39738
mistral_extra_git_track_branch: stable/yoga

## Murano service
murano_git_repo: https://opendev.org/openstack/murano
murano_git_install_branch: 6b3211357b60e7200e5efe48e5cfc89bf6e8f278
murano_git_track_branch: stable/yoga

murano_dashboard_git_repo: https://opendev.org/openstack/murano-dashboard
murano_dashboard_git_install_branch: 06c357a470198e132617e72a8a9db9e0190d50f5
murano_dashboard_git_track_branch: stable/yoga

## Trove service
trove_git_repo: https://opendev.org/openstack/trove
trove_git_install_branch: df06873242f35e33dd873cd7076914cea1cf4058
trove_git_track_branch: stable/yoga

## Horizon Trove dashboard plugin
trove_dashboard_git_repo: https://opendev.org/openstack/trove-dashboard
trove_dashboard_git_install_branch: 8aa63e73453b5953068e9b511cbd759d20f0a690
trove_dashboard_git_track_branch: stable/yoga


## Octavia service
octavia_git_repo: https://opendev.org/openstack/octavia
octavia_git_install_branch: c662e42b849aa962a814fe756e109950e794277c
octavia_git_track_branch: stable/yoga


## Placement service
placement_git_repo: https://opendev.org/openstack/placement
placement_git_install_branch: 4d3df47ee3e394e3178d58c15306620809ad2806
placement_git_track_branch: stable/yoga


## Tacker service
tacker_git_repo: https://opendev.org/openstack/tacker
tacker_git_install_branch: 2625c00375bb0ae407ecfb8ac60f80d6b10f5305
tacker_git_track_branch: stable/yoga


## Horizon Octavia dashboard plugin
octavia_dashboard_git_repo: https://opendev.org/openstack/octavia-dashboard
octavia_dashboard_git_install_branch: 127294f10d0fcd718a519d8a957bac55504023c5
octavia_dashboard_git_track_branch: stable/yoga


## Blazar service
blazar_git_repo: https://opendev.org/openstack/blazar
blazar_git_install_branch: 590730a1d79992133874250f09f884a1aca39b5a
blazar_git_track_branch: stable/yoga

## Blazar Nova Service
blazar_nova_git_repo: https://opendev.org/openstack/blazar-nova
blazar_nova_git_install_branch: f7a8f9c8076dc26936ce6ffaa2567f729c60d863
blazar_nova_git_track_branch: stable/yoga

## Zun service
zun_git_repo: https://opendev.org/openstack/zun
zun_git_install_branch: e0d0c28dccdfd9ed975ec02cfcdb1f2a7186a516
zun_git_track_branch: stable/yoga

## Zun kuryr service
zun_kuryr_git_repo: https://opendev.org/openstack/kuryr-libnetwork
zun_kuryr_git_install_branch: 49078002d6575ec6ba4121c3b3fe8d6517ba36e3
zun_kuryr_git_track_branch: stable/yoga

## Zun kuryr library
zun_kuryr_lib_git_repo: https://opendev.org/openstack/kuryr
zun_kuryr_lib_git_install_branch: 96b0991f79a0b16c3cef9161c0d171ddbe0d0327
zun_kuryr_lib_git_track_branch: stable/yoga
